package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.JoinColumn;
import javax.persistence.Table;

/**
 * Analyseur generated by hbm2java
 */
@Entity
@Table(name = "analyseur", catalog = "neo3")
@Inheritance(strategy=InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name="DTYPE")
public class Analyseur implements java.io.Serializable {

	private int idAnalyseur;
	private String type;
	private String libel;
	private Set<LangageNaturel> langageNaturels = new HashSet<LangageNaturel>(0);
	private Set<Curriculumvitae> cvs=new HashSet<>(0);
	

	public Analyseur() {
	}



	public Analyseur(int idAnalyseur, String type, String libel, Set<LangageNaturel> langageNaturels) {
		this.idAnalyseur = idAnalyseur;
		this.type = type;
		this.libel = libel;
		this.langageNaturels = langageNaturels;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idAnalyseur", unique = true, nullable = false)
	public int getIdAnalyseur() {
		return this.idAnalyseur;
	}

	public void setIdAnalyseur(int idAnalyseur) {
		this.idAnalyseur = idAnalyseur;
	}

	@Column(name = "type", length = 254)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "libel", length = 254)
	public String getLibel() {
		return this.libel;
	}

	public void setLibel(String libel) {
		this.libel = libel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "analyseur")
	public Set<LangageNaturel> getLangageNaturels() {
		return this.langageNaturels;
	}

	public void setLangageNaturels(Set<LangageNaturel> langageNaturels) {
		this.langageNaturels = langageNaturels;
	}
	
	@ManyToMany(cascade = CascadeType.ALL)
	@JoinTable(name= "WorkOn",
	joinColumns={@JoinColumn(name="AnalyseurID")},
	inverseJoinColumns={@JoinColumn(name="CV_ID")})	
	public Set<Curriculumvitae> getCvs() {
		return cvs;
	}
	public void setCvs(Set<Curriculumvitae> cvs) {
		this.cvs = cvs;
	}
}
