package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AutorisationConge generated by hbm2java
 */
@Entity
@Table(name = "autorisation_conge", catalog = "neo3")
public class AutorisationConge implements java.io.Serializable {

	private int idDoc;
	private Employe employe;
	private String titre;
	private String type;
	private Date dateCreation;
	private String description;
	private String objectif;

	public AutorisationConge() {
	}

	public AutorisationConge(int idDoc, Employe employe) {
		this.idDoc = idDoc;
		this.employe = employe;
	}

	public AutorisationConge(int idDoc, Employe employe, String titre, String type, Date dateCreation,
			String description, String objectif) {
		this.idDoc = idDoc;
		this.employe = employe;
		this.titre = titre;
		this.type = type;
		this.dateCreation = dateCreation;
		this.description = description;
		this.objectif = objectif;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idDoc", unique = true, nullable = false)
	public int getIdDoc() {
		return this.idDoc;
	}

	public void setIdDoc(int idDoc) {
		this.idDoc = idDoc;
	}

	@ManyToOne(fetch = FetchType.EAGER,cascade = {CascadeType.DETACH})
	@JoinColumn(name = "CIN", nullable = true)
	public Employe getEmploye() {
		return this.employe;
	}

	public void setEmploye(Employe employe) {
		this.employe = employe;
	}

	@Column(name = "titre", length = 254)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Column(name = "Type", length = 254)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCreation", length = 19)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "Description", length = 254)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "objectif", length = 254)
	public String getObjectif() {
		return this.objectif;
	}

	public void setObjectif(String objectif) {
		this.objectif = objectif;
	}

}
