package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CarriereId generated by hbm2java
 */
@Embeddable
public class CarriereId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String cin;
	private int idExpe;

	public CarriereId() {
	}

	public CarriereId(String cin, int idExpe) {
		this.cin = cin;
		this.idExpe = idExpe;
	}

	@Column(name = "CIN", nullable = false)
	public String getCin() {
		return this.cin;
	}

	public void setCin(String cin) {
		this.cin = cin;
	}

	@Column(name = "idExpe", nullable = false)
	public int getIdExpe() {
		return this.idExpe;
	}

	public void setIdExpe(int idExpe) {
		this.idExpe = idExpe;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cin == null) ? 0 : cin.hashCode());
		result = prime * result + idExpe;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CarriereId other = (CarriereId) obj;
		if (cin == null) {
			if (other.cin != null)
				return false;
		} else if (!cin.equals(other.cin))
			return false;
		if (idExpe != other.idExpe)
			return false;
		return true;
	}



}
