package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;

import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Carriere generated by hbm2java
 */
@Entity
@Table(name = "carriere", catalog = "neo3")
public class Carriere implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private CarriereId id;
	private Candidat candidat;
	private Date dateDep;
	private Date dateFin;
	private String niveau;
	private String societe;
	
	public Carriere() {
	}
	
	/**
	 * @param id
	 * @param dateDep
	 * @param dateFin
	 * @param niveau
	 * @param societe
	 */
	public Carriere(CarriereId id, Date dateDep, Date dateFin, String niveau, String societe) {
		super();
		this.id = id;
		this.dateDep = dateDep;
		this.dateFin = dateFin;
		this.niveau = niveau;
		this.societe = societe;
	}

	public Carriere(CarriereId id, Candidat candidat) {
		this.id = id;
		this.candidat = candidat;
	}

	public Carriere(CarriereId id, Candidat candidat, Date dateDep, Date dateFin, String niveau, String societe) {
		this.id = id;
		this.candidat = candidat;
		this.dateDep = dateDep;
		this.dateFin = dateFin;
		this.niveau = niveau;
		this.societe = societe;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "cin", column = @Column(name = "CIN", nullable = false)),
			@AttributeOverride(name = "idExpe", column = @Column(name = "idExpe", nullable = false)) })
	public CarriereId getId() {
		return this.id;
	}

	public void setId(CarriereId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CIN", nullable = false, insertable = false, updatable = false)
	public Candidat getCandidat() {
		return this.candidat;
	}

	public void setCandidat(Candidat candidat) {
		this.candidat = candidat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateDep", length = 19)
	public Date getDateDep() {
		return this.dateDep;
	}

	public void setDateDep(Date dateDep) {
		this.dateDep = dateDep;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateFin", length = 19)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	@Column(name = "niveau", length = 254)
	public String getNiveau() {
		return this.niveau;
	}

	public void setNiveau(String niveau) {
		this.niveau = niveau;
	}

	@Column(name = "societe", length = 254)
	public String getSociete() {
		return this.societe;
	}

	public void setSociete(String societe) {
		this.societe = societe;
	}

	@Override
	public String toString() {
		return "Carriere [id=" + id + ", dateDep=" + dateDep + ", dateFin=" + dateFin + ", niveau=" + niveau
				+ ", societe=" + societe + "]";
	}
	

}
