package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorytest generated by hbm2java
 */
@Entity
@Table(name = "categorytest", catalog = "neo3")
public class Categorytest implements java.io.Serializable {

	private int idCatego;
	private String libelle;
	private Set<Test> tests = new HashSet<Test>(0);

	public Categorytest() {
	}

	public Categorytest(int idCatego) {
		this.idCatego = idCatego;
	}

	public Categorytest(int idCatego, String libelle, Set<Test> tests) {
		this.idCatego = idCatego;
		this.libelle = libelle;
		this.tests = tests;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idCatego", unique = true, nullable = false)
	public int getIdCatego() {
		return this.idCatego;
	}

	public void setIdCatego(int idCatego) {
		this.idCatego = idCatego;
	}

	@Column(name = "Libelle", length = 254)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorytest")
	public Set<Test> getTests() {
		return this.tests;
	}

	public void setTests(Set<Test> tests) {
		this.tests = tests;
	}

}
