package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Competence generated by hbm2java
 */
@Entity
@Table(name = "competence", catalog = "neo3")
public class Competence implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idCompetence;
	private String type;
	private String tag;

	public Competence() {
	}

	public Competence(int idCompetence) {
		this.idCompetence = idCompetence;
	}

	public Competence(int idCompetence, String type, String tag) {
		this.idCompetence = idCompetence;
		this.type = type;
		this.tag = tag;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idCompetence", unique = true, nullable = false)
	public int getIdCompetence() {
		return this.idCompetence;
	}

	public void setIdCompetence(int idCompetence) {
		this.idCompetence = idCompetence;
	}

	@Column(name = "type", length = 254)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "tag", length = 254)
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	/**
	 * @param type
	 * @param tag
	 */
	public Competence(String type, String tag) {
		super();
		this.type = type;
		this.tag = tag;
	}

	@Override
	public String toString() {
		return "Competence [idCompetence=" + idCompetence + ", type=" + type + ", tag=" + tag + "]";
	}

}
