package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Conge generated by hbm2java
 */
@Entity
@Table(name = "conge", catalog = "neo3")
public class Conge implements java.io.Serializable {

	private int idConge;
	private Employe employe;
	private String raison;
	private String type;
	private Date dateDebut;
	private Date dateFin;
	private String etat;
	private String motifs;

	public Conge() {
	}

	public Conge(int idConge, Employe employe) {
		this.idConge = idConge;
		this.employe = employe;
	}

	public Conge(int idConge, Employe employe, String raison, String type, Date dateDebut, Date dateFin, String etat,
			String motifs) {
		this.idConge = idConge;
		this.employe = employe;
		this.raison = raison;
		this.type = type;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.etat = etat;
		this.motifs = motifs;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idConge", unique = true, nullable = false)
	public int getIdConge() {
		return this.idConge;
	}

	public void setIdConge(int idConge) {
		this.idConge = idConge;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CIN", nullable = false)
	public Employe getEmploye() {
		return this.employe;
	}

	public void setEmploye(Employe employe) {
		this.employe = employe;
	}

	@Column(name = "raison", length = 254)
	public String getRaison() {
		return this.raison;
	}

	public void setRaison(String raison) {
		this.raison = raison;
	}

	@Column(name = "type", length = 254)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateDebut", length = 19)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateFin", length = 19)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	@Column(name = "etat", length = 254)
	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	@Column(name = "motifs", length = 254)
	public String getMotifs() {
		return this.motifs;
	}

	public void setMotifs(String motifs) {
		this.motifs = motifs;
	}

}
