package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import java.util.Date;

import javax.persistence.CascadeType;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlTransient;


/**
 * Contrat generated by hbm2java
 */
@Entity
@Table(name = "contrat", catalog = "neo3")

public class Contrat implements java.io.Serializable {






	private static final long serialVersionUID = 1L;

	private int idContrat;
	private Salaire salaire;
	private Date dateDep;
	private Date dateFin;
	private String type;

	private Employe employe;

	public Contrat() {
	}


	public Contrat(Date dateDep, Date dateFin, String type, Employe employe) {
		super();
		this.dateDep = dateDep;
		this.dateFin = dateFin;
		this.type = type;
		this.employe = employe;
	}

	public Contrat(int idContrat, Salaire salaire, Date dateDep, Date dateFin, String type) {
		super();
		this.idContrat = idContrat;
		this.salaire = salaire;
		this.dateDep = dateDep;
		this.dateFin = dateFin;
		this.type = type;
	}





	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idContrat", unique = true, nullable = false)
	public int getIdContrat() {
		return this.idContrat;
	}

	public void setIdContrat(int idContrat) {
		this.idContrat = idContrat;
	}
	
	@OneToOne
	@JoinColumn(name = "idEmploye")
	public Employe getEmploye() {
		return employe;
	}

	public void setEmploye(Employe employe) {
		this.employe = employe;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idSalaire")
	public Salaire getSalaire() {
		return this.salaire;
	}

	public void setSalaire(Salaire salaire) {
		this.salaire = salaire;
	}

	@Column(name = "DateDep", length = 19)
	public Date getDateDep() {
		return this.dateDep;
	}

	public void setDateDep(Date dateDep) {
		this.dateDep = dateDep;
	}

	@Column(name = "DateFin", length = 19)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	@Column(name = "Type", length = 254)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}




	@Override
	public String toString() {
		return "Contrat [idContrat=" + idContrat + ", salaire=" + salaire + ", dateDep=" + dateDep + ", dateFin="
				+ dateFin + ", type=" + type  + "]";
	}






}
