package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;



/**
 * Curriculumvitae generated by hbm2java
 */
@Entity
@Table(name = "curriculumvitae", catalog = "neo3")
public class Curriculumvitae implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idCv;
	private String blocExperience;
	private String blocCompetence;
	private String blocDiplome;
	private String blocInfosPersonnel;
	private String contenu;
	private String path;
	private Candidat candidat;
	public Curriculumvitae() {
	}

	public Curriculumvitae(int idCv) {
		this.idCv = idCv;
		
	}

	public Curriculumvitae(int idCv,  String blocExperience, String blocCompetence, String blocDiplome,
			String blocInfosPersonnel, String contenu, String path, Candidat  candidat) {
		this.idCv = idCv;
		this.blocExperience = blocExperience;
		this.blocCompetence = blocCompetence;
		this.blocDiplome = blocDiplome;
		this.blocInfosPersonnel = blocInfosPersonnel;
		this.contenu = contenu;
		this.path = path;
		this.candidat = candidat;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idCV", unique = true, nullable = false)
	public int getIdCv() {
		return this.idCv;
	}

	public void setIdCv(int idCv) {
		this.idCv = idCv;
	}

	

	@Column(name = "blocExperience", length = 254)
	public String getBlocExperience() {
		return this.blocExperience;
	}

	public void setBlocExperience(String blocExperience) {
		this.blocExperience = blocExperience;
	}

	@Column(name = "blocCompetence", length = 254)
	public String getBlocCompetence() {
		return this.blocCompetence;
	}

	public void setBlocCompetence(String blocCompetence) {
		this.blocCompetence = blocCompetence;
	}

	@Column(name = "blocDiplome", length = 254)
	public String getBlocDiplome() {
		return this.blocDiplome;
	}

	public void setBlocDiplome(String blocDiplome) {
		this.blocDiplome = blocDiplome;
	}

	@Column(name = "blocInfosPersonnel", length = 254)
	public String getBlocInfosPersonnel() {
		return this.blocInfosPersonnel;
	}

	public void setBlocInfosPersonnel(String blocInfosPersonnel) {
		this.blocInfosPersonnel = blocInfosPersonnel;
	}
	
	@Column(name = "contenu", length = 254)
	public String getContenu() {
		return this.contenu;
	}
	
	public void setContenu(String contenu) {
		this.contenu = contenu;
	}

	@Column(name = "path", length = 254)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}
	
	@OneToOne
	public Candidat getCandidat() {
		return candidat;
	}
	
	public void setCandidat(Candidat candidat) {
		this.candidat = candidat;
	}	

}
