package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CursusId generated by hbm2java
 */
@Embeddable
public class CursusId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int diplomeId;
	private String cin;

	public CursusId() {
	}

	public CursusId(int diplomeId, String cin) {
		this.diplomeId = diplomeId;
		this.cin = cin;
	}

	@Column(name = "diplomeId", nullable = false)
	public int getDiplomeId() {
		return this.diplomeId;
	}

	public void setDiplomeId(int diplomeId) {
		this.diplomeId = diplomeId;
	}

	@Column(name = "CIN", nullable = false)
	public String getCin() {
		return this.cin;
	}

	public void setCin(String cin) {
		this.cin = cin;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cin == null) ? 0 : cin.hashCode());
		result = prime * result + diplomeId;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CursusId other = (CursusId) obj;
		if (cin == null) {
			if (other.cin != null)
				return false;
		} else if (!cin.equals(other.cin))
			return false;
		if (diplomeId != other.diplomeId)
			return false;
		return true;
	}



}
