package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cursus generated by hbm2java
 */
@Entity
@Table(name = "cursus", catalog = "neo3")
public class Cursus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private CursusId id;
	private Candidat candidat;
	private Date anneeDeb;
	private Date anneeFin;
	private String mention;

	public Cursus() {
	}

	public Cursus(CursusId id, Candidat candidat) {
		this.id = id;
		this.candidat = candidat;
	}
	
	/**
	 * @param anneeDeb
	 * @param anneeFin
	 * @param mention
	 */
	public Cursus(Date anneeDeb, Date anneeFin, String mention) {
		super();
		
		this.anneeDeb = anneeDeb;
		this.anneeFin = anneeFin;
		this.mention = mention;
	}

	/**
	 * @param id
	 * @param anneeDeb
	 * @param anneeFin
	 * @param mention
	 */
	public Cursus(CursusId id, Date anneeDeb, Date anneeFin, String mention) {
		super();
		this.id = id;
		this.anneeDeb = anneeDeb;
		this.anneeFin = anneeFin;
		this.mention = mention;
	}

	public Cursus(CursusId id, Candidat candidat, Date anneeDeb, Date anneeFin, String mention) {
		this.id = id;
		this.candidat = candidat;
		this.anneeDeb = anneeDeb;
		this.anneeFin = anneeFin;
		this.mention = mention;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "diplomeId", column = @Column(name = "diplomeId", nullable = false)),
			@AttributeOverride(name = "cin", column = @Column(name = "CIN", nullable = false)) })
	public CursusId getId() {
		return this.id;
	}

	public void setId(CursusId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CIN", nullable = false, insertable = false, updatable = false)
	public Candidat getCandidat() {
		return this.candidat;
	}

	public void setCandidat(Candidat candidat) {
		this.candidat = candidat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "anneeDeb", length = 19)
	public Date getAnneeDeb() {
		return this.anneeDeb;
	}

	public void setAnneeDeb(Date anneeDeb) {
		this.anneeDeb = anneeDeb;
	}

	@Column(name = "anneeFin", length = 254)
	public Date getAnneeFin() {
		return this.anneeFin;
	}

	public void setAnneeFin(Date anneeFin) {
		this.anneeFin = anneeFin;
	}

	@Column(name = "Mention", length = 254)
	public String getMention() {
		return this.mention;
	}

	public void setMention(String mention) {
		this.mention = mention;
	}

	@Override
	public String toString() {
		return "Cursus [id=" + id + ", anneeDeb=" + anneeDeb + ", anneeFin=" + anneeFin + ", mention=" + mention + "]";
	}
	
}
