package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Departement generated by hbm2java
 */
@Entity
@Table(name = "departement", catalog = "neo3")
public class Departement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int idDep;
	private String libelleDep;
	
	private Set<Employe> employes = new HashSet<Employe>(0);

	public Departement() {
	}

	
	@Override
	public String toString() {
		return "Departement [libelleDep=" + libelleDep + "]";
	}


	public Departement(int idDep, String libelleDep) {
		this.idDep = idDep;
		this.libelleDep = libelleDep;
	}

	
	
	public Departement(String libelleDep) {
		this.libelleDep = libelleDep;
	}


	public Departement(int idDep, String libelleDep, Set<Employe> employes) {
		this.idDep = idDep;
		this.libelleDep = libelleDep;
		this.employes = employes;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idDep", unique = true, nullable = false)
	public int getIdDep() {
		return this.idDep;
	}

	public void setIdDep(int idDep) {
		this.idDep = idDep;
	}

	@Column(name = "libelleDEp", length = 254)
	public String getLibelleDep() {
		return this.libelleDep;
	}

	public void setLibelleDep(String libelleDep) {
		this.libelleDep = libelleDep;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "departement")
	public Set<Employe> getEmployes() {
		return this.employes;
	}

	public void setEmployes(Set<Employe> employes) {
		this.employes = employes;
	}

}
