package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Diplome generated by hbm2java
 */
@Entity
@Table(name = "diplome", catalog = "neo3")
public class Diplome implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int diplomeId;
	private Ecole ecole;
	private Employe employe;
	private String type;
	private String nom;

	public Diplome() {
	}

	public Diplome(int diplomeId, Ecole ecole, Employe employe) {
		this.diplomeId = diplomeId;
		this.ecole = ecole;
		this.employe = employe;
	}

	public Diplome(int diplomeId, Ecole ecole, Employe employe, String type, String nom) {
		this.diplomeId = diplomeId;
		this.ecole = ecole;
		this.employe = employe;
		this.type = type;
		this.nom = nom;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "diplomeId", unique = true,nullable=false)
	public int getDiplomeId() {
		return this.diplomeId;
	}

	public void setDiplomeId(int diplomeId) {
		this.diplomeId = diplomeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEcole", nullable = true)
	public Ecole getEcole() {
		return this.ecole;
	}

	public void setEcole(Ecole ecole) {
		this.ecole = ecole;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CIN", nullable = true)
	public Employe getEmploye() {
		return this.employe;
	}

	public void setEmploye(Employe employe) {
		this.employe = employe;
	}

	@Column(name = "type", length = 254)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	/**
	 * @param type
	 * @param nom
	 */
	public Diplome(String type, String nom) {
		super();
		this.type = type;
		this.nom = nom;
	}

	@Override
	public String toString() {
		return "Diplome [diplomeId=" + diplomeId + ", type=" + type + ", nom=" + nom + "]";
	}
	

}
