package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Evenement generated by hbm2java
 */
@Entity
@Table(name = "evenement", catalog = "neo3")
public class Evenement implements java.io.Serializable {

	private int idEvent;
	private Employe employe;
	private String libelle;
	private String description;
	private String type;
	private String lieu;

	public Evenement() {
	}

	public Evenement(int idEvent, Employe employe) {
		this.idEvent = idEvent;
		this.employe = employe;
	}

	public Evenement(int idEvent, Employe employe, String libelle, String description, String type, String lieu) {
		this.idEvent = idEvent;
		this.employe = employe;
		this.libelle = libelle;
		this.description = description;
		this.type = type;
		this.lieu = lieu;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idEvent", unique = true, nullable = false)
	public int getIdEvent() {
		return this.idEvent;
	}

	public void setIdEvent(int idEvent) {
		this.idEvent = idEvent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CIN", nullable = false)
	public Employe getEmploye() {
		return this.employe;
	}

	public void setEmploye(Employe employe) {
		this.employe = employe;
	}

	@Column(name = "libelle", length = 254)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "Description", length = 254)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Type", length = 254)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "lieu", length = 254)
	public String getLieu() {
		return this.lieu;
	}

	public void setLieu(String lieu) {
		this.lieu = lieu;
	}

}
