package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Experience generated by hbm2java
 */
@Entity
@Table(name = "experience", catalog = "neo3")
public class Experience implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idExpe;
	private String nom;
	private String type;

	public Experience() {
	}

	public Experience(int idExpe) {
		this.idExpe = idExpe;
	}

	public Experience(int idExpe, String nom, String type) {
		this.idExpe = idExpe;
		this.nom = nom;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idExpe", unique = true, nullable = false)
	public int getIdExpe() {
		return this.idExpe;
	}

	public void setIdExpe(int idExpe) {
		this.idExpe = idExpe;
	}

	@Column(name = "Nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	
	@Column(name = "Type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	/**
	 * @param nom
	 * @param type
	 */
	public Experience(String nom, String type) {
		super();
		this.nom = nom;
		this.type = type;
	}

	@Override
	public String toString() {
		return "Experience [idExpe=" + idExpe + ", nom=" + nom + ", type=" + type + "]";
	}
	
	
}
