package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Grade generated by hbm2java
 */
@Entity
@Table(name = "grade", catalog = "neo3")
public class Grade implements java.io.Serializable {
	
	

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idGrade;
    private String libelleGrade;
    
    
	private Set<Employe> employes = new HashSet<Employe>(0);

	public Grade() {
	}

	public Grade(int idGrade) {
		this.idGrade = idGrade;
	}
	
	public Grade(int idGrade, String libelleGrade) {
		this.idGrade = idGrade;
		this.libelleGrade = libelleGrade;
	}
	
	public Grade(String libelleGrade) {
		this.libelleGrade = libelleGrade;
	}

	public Grade(int idGrade, String libelleGrade, Set<Employe> employes) {
		this.idGrade = idGrade;
		this.libelleGrade = libelleGrade;
		this.employes = employes;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idGrade", unique = true, nullable = false)
	public int getIdGrade() {
		return this.idGrade;
	}

	public void setIdGrade(int idGrade) {
		this.idGrade = idGrade;
	}

	@Column(name = "libelleGrade", length = 254)
	public String getLibelleGrade() {
		return this.libelleGrade;
	}

	public void setLibelleGrade(String libelleGrade) {
		this.libelleGrade = libelleGrade;
	}
	@JsonBackReference
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "grade")
	public Set<Employe> getEmployes() {
		return this.employes;
	}

	public void setEmployes(Set<Employe> employes) {
		this.employes = employes;
	}
	
	@Override
	public String toString() {
		return "Grade [idGrade=" + idGrade + ", libelleGrade=" + libelleGrade + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((employes == null) ? 0 : employes.hashCode());
		result = prime * result + idGrade;
		result = prime * result + ((libelleGrade == null) ? 0 : libelleGrade.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Grade other = (Grade) obj;
		if (employes == null) {
			if (other.employes != null)
				return false;
		} else if (!employes.equals(other.employes))
			return false;
		if (idGrade != other.idGrade)
			return false;
		if (libelleGrade == null) {
			if (other.libelleGrade != null)
				return false;
		} else if (!libelleGrade.equals(other.libelleGrade))
			return false;
		return true;
	}

	
}
