package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * ManagerFrance generated by hbm2java
 */
@Entity
@Table(name = "manager_france", catalog = "neo3")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class,
property ="cin")
public class ManagerFrance implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String cin;
	private String nom;
	private String prenom;
	private String email;
	private String numTel;
	private String adresse;
	private String perEmail;
	private Set<Employe> employes = new HashSet<Employe>(0);

	public ManagerFrance() {
	}

	public ManagerFrance(String cin) {
		this.cin = cin;
	}

	public ManagerFrance(String cin, String nom, String prenom, String email, String numTel, String adresse,
			String perEmail, Set<Employe> employes) {
		this.cin = cin;
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
		this.numTel = numTel;
		this.adresse = adresse;
		this.perEmail = perEmail;
		this.employes = employes;
	}

	@Id

	@Column(name = "CIN", unique = true, nullable = false)
	public String getCin() {
		return this.cin;
	}

	public void setCin(String cin) {
		this.cin = cin;
	}

	@Column(name = "Nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "Prenom", length = 254)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "Email", length = 254)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "numTel", length = 254)
	public String getNumTel() {
		return this.numTel;
	}

	public void setNumTel(String numTel) {
		this.numTel = numTel;
	}

	@Column(name = "adresse", length = 254)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "Per_email", length = 254)
	public String getPerEmail() {
		return this.perEmail;
	}

	public void setPerEmail(String perEmail) {
		this.perEmail = perEmail;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "managerFrance")
	public Set<Employe> getEmployes() {
		return this.employes;
	}

	public void setEmployes(Set<Employe> employes) {
		this.employes = employes;
	}

}
