package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mot generated by hbm2java
 */
@Entity
@Table(name = "mot", catalog = "neo3")
@Inheritance(strategy=InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name="DTYPE")
public class Mot implements java.io.Serializable {

	private int idMot;
	private LangageNaturel langageNaturel;
	private String pattern;
	private String label;

	public Mot() {
	}

	public Mot(int idMot, LangageNaturel langageNaturel) {
		this.idMot = idMot;
		this.langageNaturel = langageNaturel;
	}

	public Mot(int idMot, LangageNaturel langageNaturel, String pattern, String label) {
		this.idMot = idMot;
		this.langageNaturel = langageNaturel;
		this.pattern = pattern;
		this.label = label;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idMot", unique = true, nullable = false)
	public int getIdMot() {
		return this.idMot;
	}

	public void setIdMot(int idMot) {
		this.idMot = idMot;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idLang", nullable = false)
	public LangageNaturel getLangageNaturel() {
		return this.langageNaturel;
	}

	public void setLangageNaturel(LangageNaturel langageNaturel) {
		this.langageNaturel = langageNaturel;
	}

	@Column(name = "pattern", length = 254)
	public String getPattern() {
		return this.pattern;
	}

	public void setPattern(String pattern) {
		this.pattern = pattern;
	}

	@Column(name = "label", length = 254)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

}
