package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Note generated by hbm2java
 */
@Entity
@Table(name = "note", catalog = "neo3")
public class Note implements java.io.Serializable {

	private int idNote;
	private Integer Note;
	private Employe employe;

	public Note() {
	}

	public Note(int idNote) {
		this.idNote = idNote;
	}

	public Note(int idNote, Employe employe) {
		this.idNote = idNote;
		this.employe = employe;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idNote", unique = true, nullable = false)
	public int getIdNote() {
		return this.idNote;
	}

	public void setIdNote(int idNote) {
		this.idNote = idNote;
	}
	
	@Column(name = "note")
	public Integer getNote() {
		return Note;
	}

	public void setNote(Integer note) {
		this.Note = note;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CIN")
	public Employe getEmploye() {
		return this.employe;
	}

	public void setEmploye(Employe employe) {
		this.employe = employe;
	}

	@Override
	public String toString() {
		return "Note [idNote=" + idNote + "]";
	}

}
