package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Produit generated by hbm2java
 */
@Entity
@Table(name = "produit", catalog = "neo3")

public class Produit implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idPro;
	private String nom;
	private String type;
	private Date datedeDebut;
	private Date datefin;
	private Set<Equipe> equipes = new HashSet<Equipe>(0);
	private List<Stagiaire> stagiaires;

	@OneToMany(fetch = FetchType.EAGER)
	public List<Stagiaire> getStagiaires() {
		return this.stagiaires;
	}

	public void setStagiaires(List<Stagiaire> stagiaires) {
		this.stagiaires = stagiaires;
	}

	public Produit() {
	}

	public Produit(int idPro) {
		this.idPro = idPro;
	}

	public Produit(int idPro, String nom, String type, Date datedeDebut, Date datefin) {
		this.idPro = idPro;
		this.nom = nom;
		this.type = type;
		this.datedeDebut = datedeDebut;
		this.datefin = datefin;

	}

	public Produit(String nom, String type, Date datedeDebut, Date datefin) {

		this.nom = nom;
		this.type = type;
		this.datedeDebut = datedeDebut;
		this.datefin = datefin;

	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idPro", unique = true, nullable = false)
	public int getIdPro() {
		return this.idPro;
	}

	public void setIdPro(int idPro) {
		this.idPro = idPro;
	}
	@JsonProperty
	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}
	@JsonProperty
	@Column(name = "type", length = 254)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}
    @JsonProperty
	@Temporal(TemporalType.DATE)
	@Column(name = "datedeDebut", length = 19)
	public Date getDatedeDebut() {
		return this.datedeDebut;
	}

	public void setDatedeDebut(Date datedeDebut) {
		this.datedeDebut = datedeDebut;
	}
	@JsonProperty
	@Temporal(TemporalType.DATE)
	@Column(name = "datefin", length = 19)
	public Date getDatefin() {
		return this.datefin;
	}

	public void setDatefin(Date datefin) {
		this.datefin = datefin;
	}
	//  @OneToMany(fetch = FetchType.LAZY, mappedBy = "produit")
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "produit")
	///@JoinColumn(name = "idEquipe")
	public  Set<Equipe> getEquipes() { return this.equipes; }

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public void setEquipes(Set<Equipe> equipes) {
		this.equipes = equipes;
	}
	 

	

}
