package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Reclamation generated by hbm2java
 */
@Entity
@Table(name = "reclamation", catalog = "neo3")
public class Reclamation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int idReclamation;
	private Employe employeByCin;
	private Employe employeByEmpCin;
	private String description;
	private Date dateCreation;
	private String motifs;
	private Date dateTraitement;
	private String etat;
	private String commentaire;
	public Reclamation() {
	}

	public Reclamation(int idReclamation) {
		this.idReclamation = idReclamation;
	}




	public Reclamation(int idReclamation, Employe employeByCin, Employe employeByEmpCin, String description,
			Date dateCreation, String motifs, Date dateTraitement) {
		super();
		this.idReclamation = idReclamation;
		this.employeByCin = employeByCin;
		this.employeByEmpCin = employeByEmpCin;
		this.description = description;
		this.dateCreation = dateCreation;
		this.motifs = motifs;
		this.dateTraitement = dateTraitement;
	}



	public Reclamation(Employe employeByCin, String description, Date dateCreation, String motifs) {
		super();
		this.employeByCin = employeByCin;
		this.description = description;
		this.dateCreation = dateCreation;
		this.motifs = motifs;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idReclamation", unique = true, nullable = false)
	public int getIdReclamation() {
		return this.idReclamation;
	}

	public void setIdReclamation(int idReclamation) {
		this.idReclamation = idReclamation;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CIN")
	public Employe getEmployeByCin() {
		return this.employeByCin;
	}

	public void setEmployeByCin(Employe employeByCin) {
		this.employeByCin = employeByCin;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Emp_CIN")
	public Employe getEmployeByEmpCin() {
		return this.employeByEmpCin;
	}

	public void setEmployeByEmpCin(Employe employeByEmpCin) {
		this.employeByEmpCin = employeByEmpCin;
	}

	@Column(name = "description", length = 254)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "dateCreation")
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "motifs", length = 254)
	public String getMotifs() {
		return this.motifs;
	}

	public void setMotifs(String motifs) {
		this.motifs = motifs;
	}

	@Column(name = "DateTraitement")
	public Date getDateTraitement() {
		return dateTraitement;
	}

	public void setDateTraitement(Date dateTraitement) {
		this.dateTraitement = dateTraitement;
	}

	public String getEtat() {
		return etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public String getCommentaire() {
		return commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	@Override
	public String toString() {
		return "Reclamation [idReclamation=" + idReclamation + ", employeByCin=" + employeByCin + ", employeByEmpCin="
				+ employeByEmpCin + ", description=" + description + ", dateCreation=" + dateCreation + ", motifs="
				+ motifs + ", dateTraitement=" + dateTraitement + "]";
	}



}
