package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Salaire generated by hbm2java
 */
@Entity
@Table(name = "salaire", catalog = "neo3")
public class Salaire implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idSalaire;
	private Integer salaireBrut;
	private Integer salaireNet;
	private Date moisEtAnne;
	private Integer bonus;
	private Date dateCreation;
	private Set<Contrat> contrats = new HashSet<Contrat>(0);

	public Salaire() {
	}


	public Salaire(int idSalaire, Integer salaireBrut, Integer salaireNet, Date moisEtAnne, Integer bonus,
			Date dateCreation, Set<Contrat> contrats) {
		this.idSalaire = idSalaire;
		this.salaireBrut = salaireBrut;
		this.salaireNet = salaireNet;
		this.moisEtAnne = moisEtAnne;
		this.bonus = bonus;
		this.dateCreation = dateCreation;
		this.contrats = contrats;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idSalaire", unique = true, nullable = false)
	public int getIdSalaire() {
		return this.idSalaire;
	}

	public void setIdSalaire(int idSalaire) {
		this.idSalaire = idSalaire;
	}

	@Column(name = "salaireBrut", precision = 8, scale = 0)
	public Integer getSalaireBrut() {
		return this.salaireBrut;
	}

	public void setSalaireBrut(Integer salaireBrut) {
		this.salaireBrut = salaireBrut;
	}

	@Column(name = "salaireNet", precision = 8, scale = 0)
	public Integer getSalaireNet() {
		return this.salaireNet;
	}

	public void setSalaireNet(Integer salaireNet) {
		this.salaireNet = salaireNet;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "moisEtAnne", length = 19)
	public Date getMoisEtAnne() {
		return this.moisEtAnne;
	}

	public void setMoisEtAnne(Date moisEtAnne) {
		this.moisEtAnne = moisEtAnne;
	}

	@Column(name = "Bonus", precision = 8, scale = 0)
	public Integer getBonus() {
		return this.bonus;
	}

	public void setBonus(Integer bonus) {
		this.bonus = bonus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCreation", length = 19)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "salaire")
	public Set<Contrat> getContrats() {
		return this.contrats;
	}

	public void setContrats(Set<Contrat> contrats) {
		this.contrats = contrats;
	}

}
