package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Skills generated by hbm2java
 */
@Entity
@Table(name = "skills", catalog = "neo3")
public class Skills implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private SkillsId id;
	private Candidat candidat;
	private String niveau;
	private String description;
	private String verifier;

	public Skills() {
	}
	
	/**
	 * @param id
	 * @param niveau
	 * @param description
	 * @param verifier
	 */
	public Skills(SkillsId id, String niveau, String description, String verifier) {
		super();
		this.id = id;
		this.niveau = niveau;
		this.description = description;
		this.verifier = verifier;
	}

	public Skills(SkillsId id, Candidat candidat) {
		this.id = id;
		this.candidat = candidat;
	}

	public Skills(SkillsId id, Candidat candidat, String niveau, String description, String verifier) {
		this.id = id;
		this.candidat = candidat;
		this.niveau = niveau;
		this.description = description;
		this.verifier = verifier;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "cin", column = @Column(name = "CIN", nullable = false)),
			@AttributeOverride(name = "idCompetence", column = @Column(name = "idCompetence", nullable = false)) })
	public SkillsId getId() {
		return this.id;
	}

	public void setId(SkillsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CIN", nullable = false, insertable = false, updatable = false)
	public Candidat getCandidat() {
		return this.candidat;
	}

	public void setCandidat(Candidat candidat) {
		this.candidat = candidat;
	}

	@Column(name = "niveau", length = 254)
	public String getNiveau() {
		return this.niveau;
	}

	public void setNiveau(String niveau) {
		this.niveau = niveau;
	}

	@Column(name = "description", length = 254)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Verifier", length = 254)
	public String getVerifier() {
		return this.verifier;
	}

	public void setVerifier(String verifier) {
		this.verifier = verifier;
	}

	@Override
	public String toString() {
		return "Skills [id=" + id + ", niveau=" + niveau + ", description=" + description + ", verifier=" + verifier
				+ "]";
	}
	

}
