package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SuivitestemployeeId generated by hbm2java
 */
@Embeddable
public class SuivitestemployeeId implements java.io.Serializable {

	private String cin;
	private int idTest;

	public SuivitestemployeeId() {
	}

	public SuivitestemployeeId(String cin, int idTest) {
		this.cin = cin;
		this.idTest = idTest;
	}

	@Column(name = "CIN", nullable = false)
	public String getCin() {
		return this.cin;
	}

	public void setCin(String cin) {
		this.cin = cin;
	}

	@Column(name = "idTest", nullable = false)
	public int getIdTest() {
		return this.idTest;
	}

	public void setIdTest(int idTest) {
		this.idTest = idTest;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cin == null) ? 0 : cin.hashCode());
		result = prime * result + idTest;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SuivitestemployeeId other = (SuivitestemployeeId) obj;
		if (cin == null) {
			if (other.cin != null)
				return false;
		} else if (!cin.equals(other.cin))
			return false;
		if (idTest != other.idTest)
			return false;
		return true;
	}



}
