package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Suivi generated by hbm2java
 */
@Entity
@Table(name = "suivi", catalog = "neo3")
public class Suivi implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * 
	 */
	private int idSuiv;
	private Employe employe;
	private String eval;
	private String entretrienTcarriere;	
	private Date DateSuivi;
	

	public Suivi() {
	}


	public Suivi(Employe employe, String eval, String entretrienTcarriere, Date dateSuivi) {
		super();
		this.employe = employe;
		this.eval = eval;
		this.entretrienTcarriere = entretrienTcarriere;
		DateSuivi = dateSuivi;
	}


	public Suivi(int idSuiv, Employe employe, String eval, String entretrienTcarriere, Date dateSuivi) {
		super();
		this.idSuiv = idSuiv;
		this.employe = employe;
		this.eval = eval;
		this.entretrienTcarriere = entretrienTcarriere;
		DateSuivi = dateSuivi;
	}



	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idSuiv", unique = true, nullable = false)
	public int getIdSuiv() {
		return this.idSuiv;
	}

	public void setIdSuiv(int idSuiv) {
		this.idSuiv = idSuiv;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CIN")
	public Employe getEmploye() {
		return this.employe;
	}

	public void setEmploye(Employe employe) {
		this.employe = employe;
	}

	@Column(name = "Eval", length = 254)
	public String getEval() {
		return this.eval;
	}

	public void setEval(String eval) {
		this.eval = eval;
	}

	@Column(name = "EntretrienTCarriere", length = 254)
	public String getEntretrienTcarriere() {
		return this.entretrienTcarriere;
	}

	public void setEntretrienTcarriere(String entretrienTcarriere) {
		this.entretrienTcarriere = entretrienTcarriere;
	}
	@Column(name = "DateSuivi")
	public Date getDateSuivi() {
		return DateSuivi;
	}

	public void setDateSuivi(Date dateSuivi) {
		DateSuivi = dateSuivi;
	}


	@Override
	public String toString() {
		return "Suivi [idSuiv=" + idSuiv + ", employe=" + employe + ", eval=" + eval + ", entretrienTcarriere="
				+ entretrienTcarriere + ", DateSuivi=" + DateSuivi + "]";
	}
	


}
