package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Suivitest generated by hbm2java
 */
@Entity
@Table(name = "suivitest", catalog = "neo3")
public class Suivitest implements java.io.Serializable {

	private SuivitestId id;
	private Candidat candidat;
	private Date date;
	private Integer resultat;
	private Date temps;

	public Suivitest() {
	}

	public Suivitest(SuivitestId id, Candidat candidat) {
		this.id = id;
		this.candidat = candidat;
	}

	public Suivitest(SuivitestId id, Candidat candidat, Date date, Integer resultat, Date temps) {
		this.id = id;
		this.candidat = candidat;
		this.date = date;
		this.resultat = resultat;
		this.temps = temps;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "cin", column = @Column(name = "CIN", nullable = false)),
			@AttributeOverride(name = "idTest", column = @Column(name = "idTest", nullable = false)) })
	public SuivitestId getId() {
		return this.id;
	}

	public void setId(SuivitestId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CIN", nullable = false, insertable = false, updatable = false)
	public Candidat getCandidat() {
		return this.candidat;
	}

	public void setCandidat(Candidat candidat) {
		this.candidat = candidat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "Resultat", precision = 8, scale = 0)
	public Integer getResultat() {
		return this.resultat;
	}

	public void setResultat(Integer resultat) {
		this.resultat = resultat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "temps", length = 19)
	public Date getTemps() {
		return this.temps;
	}

	public void setTemps(Date temps) {
		this.temps = temps;
	}

}
