package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name = "test", catalog = "neo3")
public class Test implements java.io.Serializable {

	private int idTest;
	private Categorytest categorytest;
	private String nom;
	private Date dateExpiration;
	private String type;
	private String description;
	private Set<Question> questions = new HashSet<Question>(0);

	public Test() {
	}

	public Test(int idTest) {
		this.idTest = idTest;
	}

	public Test(int idTest, Categorytest categorytest, String nom, Date dateExpiration, String type, String description,
			Set<Question> questions) {
		this.idTest = idTest;
		this.categorytest = categorytest;
		this.nom = nom;
		this.dateExpiration = dateExpiration;
		this.type = type;
		this.description = description;
		this.questions = questions;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idTest", unique = true, nullable = false)
	public int getIdTest() {
		return this.idTest;
	}

	public void setIdTest(int idTest) {
		this.idTest = idTest;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCatego")
	public Categorytest getCategorytest() {
		return this.categorytest;
	}

	public void setCategorytest(Categorytest categorytest) {
		this.categorytest = categorytest;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateExpiration", length = 19)
	public Date getDateExpiration() {
		return this.dateExpiration;
	}

	public void setDateExpiration(Date dateExpiration) {
		this.dateExpiration = dateExpiration;
	}

	@Column(name = "type", length = 254)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "description", length = 254)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "test")
	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

}
