package tn.esprit.entities;
// Generated 19 oct. 2018 22:55:32 by Hibernate Tools 5.0.6.Final

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "neo3")
public class User implements java.io.Serializable {

	public Date getLastLogin() {
		return lastLogin;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idU;
	private Candidat candidat;
	private Employe employe;
	private String username;
	private String usernameCanonical;
	private String email;
	private String emailCanonical;
	private int enabled;
	private boolean isActif;
	private String password;
	private Date lastLogin;
	private String role;
	
	public User() {
		super();
	}
     
	public User(int idU) {
		this.idU = idU;
	}
    
	
	

	public User(Candidat candidat, String username, String usernameCanonical, String email, String emailCanonical,
			int enabled, boolean isActif, String password, String role) {
		super();
		this.candidat = candidat;
		this.username = username;
		this.usernameCanonical = usernameCanonical;
		this.email = email;
		this.emailCanonical = emailCanonical;
		this.enabled = enabled;
		this.isActif = isActif;
		this.password = password;
		this.role = role;
	}
	

	public User(Employe employe, String username, String usernameCanonical, String email, String emailCanonical,
			int enabled, boolean isActif, String password, String role) {
		super();
		this.employe = employe;
		this.username = username;
		this.usernameCanonical = usernameCanonical;
		this.email = email;
		this.emailCanonical = emailCanonical;
		this.enabled = enabled;
		this.isActif = isActif;
		this.password = password;
		
		this.role = role;
	}

	public User( Candidat candidat, String username, String usernameCanonical, String email,
			String emailCanonical, int enabled, boolean isActif, String password, Date lastLogin, String role) {
		super();
		
		this.candidat = candidat;
		this.username = username;
		this.usernameCanonical = usernameCanonical;
		this.email = email;
		this.emailCanonical = emailCanonical;
		this.enabled = enabled;
		this.isActif = isActif;
		this.password = password;
		this.lastLogin = lastLogin;
		this.role = role;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idU", unique = true, nullable = false)
	public int getIdU() {
		return this.idU;
	}

	public void setIdU(int idU) {
		this.idU = idU;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CAN_CIN")
	public Candidat getCandidat() {
		return this.candidat;
	}

	public void setCandidat(Candidat candidat) {
		this.candidat = candidat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Emp_CIN")
	public Employe getEmploye() {
		return this.employe;
	}

	public void setEmploye(Employe employe) {
		this.employe = employe;
	}

	@Column(name = "username_canonical", length = 254)
	public String getUsernameCanonical() {
		return this.usernameCanonical;
	}

	public void setUsernameCanonical(String usernameCanonical) {
		this.usernameCanonical = usernameCanonical;
	}

	@Column(name = "email_canonical", length = 254)
	public String getEmailCanonical() {
		return this.emailCanonical;
	}

	public void setEmailCanonical(String emailCanonical) {
		this.emailCanonical = emailCanonical;
	}

	@Column(name = "enabled")
	public int getEnabled() {
		return this.enabled;
	}

	public void setEnabled(int enabled) {
		this.enabled = enabled;
	}

	@Column(name = "password", length = 254)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public boolean isActif() {
		return isActif;
	}

	public void setActif(boolean isActif) {
		this.isActif = isActif;
	}

	
	@Column(name = "lastLogin")
	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}
	
	

	@Column(name = "Role", length = 254)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "username", length = 254)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
